export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ADD = 'REQUEST_ADD';
export const REQUEST_ERROR_CLOSE = 'REQUEST_ERROR_CLOSE';